# This is a basic workflow to help you get started with Actions

name: Initiate Wpscan on schedule

on:
  schedule:
    - cron:  0 10 * * 1 # Monday at 10 UTC
jobs:
  wpscan:
    runs-on: ubuntu-latest
    steps:
      - name: WPScan
        uses: WTFender/wpscan-action@v1.0
        id: wpscan
        with:
          url: 'https://WORDPRESS_SITE/'          # Scan Traget URL  
          token: ${{ secrets.WPSCAN_TOKEN }}     # API token for wpscan.com. Required for vulnerability data
          webhook: ${{ secrets.SLACK_WEBHOOK }}
      - name: Scan Results
        run: |
          echo ${{ steps.wpscan.outputs.resultb64 }}  
          echo ${{ steps.wpscan.outputs.result }}
     # result: JSON scan results base64 encoded     
